### ISSUE TITLE
is this package maintained?

### ISSUE THREAD

**Issue by Goldziher** [cyyynthia/vite-plugin-magical-svg#7]

**Comment by cyyynthia** [comment]
It's not receiving many updates from me, but it isn't abandonware either so I guess that counts as still maintained...? I hope so 😅 -  I still keep an eye on bug reports and pull requests, and try to issue fix for bugs that are vital to the plugin (e.g. if something important is broken, I will do my best to work on a fix asap). No guarantees for QoL bugs though...

*Relevant meme: https://twitter.com/LunaFoxgirlVT/status/1737752888758169915*

**Comment by Goldziher** [comment]
lol

**Comment by Goldziher** [comment]
I hear you. It just feels a bit problematic to rely on it as such.

**Comment by cyyynthia** [comment]
I understand, it's a difficult choice to pick a small and not widely used tool maintained by a single person. The double-edged sword of open-source things!

I do believe this plugin falls into the category of tools that don't require much maintenance, if any. The amount of code is quite small and despite the lack of comments should be fairly easy to tweak if the necessity arises.

**Comment by Goldziher** [comment]
> I understand, it's a difficult choice to pick a small and not widely used tool maintained by a single person. The double-edged sword of open-source things!
> 
> I do believe this plugin falls into the category of tools that don't require much maintenance, if any. The amount of code is quite small and despite the lack of comments should be fairly easy to tweak if the necessity arises.

that's true. I decided to use it 😉 

Would you consider moving the package into an organization? I have this org: https://github.com/tool-belt

I would gladly add you as an owner of the org and we can have the package inside it. I want to basically use this org like the "jazz band" org from the python world.

**Comment by cyyynthia** [comment]
As I do plan on keeping an eye on the lib myself, I'd rather keep it under my account for now

For what it's worth, in a [blog post](https://cynthia.dev/blog/the-state-of-svgs-on-the-web#my-original-answer) I wrote about a year ago I said I wanted to go around and work on a potential successor to this plugin, potentially also going beyond the current feature set (and pointed out some problems this lib has, etc); I wrote a grand total of zero lines of code for that new project since then 🤪 but I still want to get around that, some day maybe...
